#ifndef PARAMS_HXAVX2
#define PARAMS_HXAVX2

#define xwing_NAMESPACE(s) xwing_ref_##s

#define DH_BYTES 32

#define XWING_SYMBYTES 32
#define XWING_SSBYTES 32
#define XWING_PUBLICKEYBYTES 1216
#define XWING_SECRETKEYBYTES 2464
#define XWING_CIPHERTEXTBYTES 1120
#define XWING_PRFINPUT 134
#define XWING_LABEL "\\.//^\\"

#endif