#ifndef PARAMS_H
#define PARAMS_H

#define DH_BYTES 32
#define LABELED_IKM_DERIVEKEYPAIR_BYTES 51
#define LABELED_IKM_EXTRACTEXXPAND_BYTES 51
#define LABELED_INFO_DERIVEKEYPAIR_BYTES 16
#define LABELED_INFO_EXTRACTEXPAND_BYTES 91
#define LABELED_IKM_OFFSET_BYTES 19
#define LABELED_INFO_OFFSET_BYTES 27
#define KEM_CONTEXT_BYTES 64

#endif
