#ifndef PARAMS_G
#define PARAMS_G

#define MLKEM_K 3
#define MLKEM_N 256
#define MLKEM_Q 3329
#define MLKEM_ETA 2
#define MLKEM_POLYBYTES 384
#define MLKEM_POLYVECBYTES 1152
#define MLKEM_POLYCOMPRESSEDBYTES 128
#define MLKEM_POLYVECCOMPRESSEDBYTES 960
#define MLKEM_INDCPA_MSGBYTES 32
#define MLKEM_INDCPA_PUBLICKEYBYTES 1184
#define MLKEM_INDCPA_SECRETKEYBYTES 1152
#define MLKEM_INDCPA_BYTES 1088
#define MLKEM_PUBLICKEYBYTES 1184
#define MLKEM_SECRETKEYBYTES 2400
#define MLKEM_CIPHERTEXTBYTES 1088
#define MLKEM_SYMBYTES 32
#define MLKEM_SSBYTES 32

#define DH_BYTES 32

#define GHPC_SYMBYTES 32
#define GHPC_SSBYTES 32
#define GHPC_PUBLICKEYBYTES MLKEM_PUBLICKEYBYTES + DH_BYTES
#define GHPC_SECRETKEYBYTES MLKEM_SECRETKEYBYTES + DH_BYTES
#define GHPC_CIPHERTEXTBYTES MLKEM_CIPHERTEXTBYTES + DH_BYTES
#define GHPC_PRFINPUT MLKEM_CIPHERTEXTBYTES + MLKEM_SSBYTES + DH_BYTES + DH_BYTES

#endif