#ifndef PARAMS_HX
#define PARAMS_HX

#define xwing_naive_NAMESPACE(s) xwing_naive_avx2_##s

#define DH_BYTES 32

#define XWING_SYMBYTES 32
#define XWING_SSBYTES 32
#define XWING_PUBLICKEYBYTES 1216
#define XWING_SECRETKEYBYTES 2464
#define XWING_CIPHERTEXTBYTES 1120
#define XWING_PRFINPUT 134 + MLKEM_CIPHERTEXTBYTES
#define XWING_LABEL "\\.//^\\"

#endif
